about_user = []
about_user.append(input("enter your name:"))
about_user.append(input("enter your surname:"))
about_user.append(input("enter your age:"))
about_user.append(input("enter your height:"))
about_user.append(input("enter your weight:"))
about_user.append(input("enter your birth age:"))
about_user.append(input("enter your nikname:"))
about_user.append(input("enter your country:"))
print(about_user)